name: sole_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  mm_swipeable: ^1.0.0+1
  lottie: ^3.1.2
  swipeable_card_stack: ^0.0.5
  provider: ^6.1.2
  flutter_card_swiper: ^7.0.1
  tutorial_coach_mark: ^1.2.11
  shared_preferences: ^2.2.3
  http: ^1.2.2
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.4
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.4.0
  flutter_datetime_picker: ^1.5.1
  google_sign_in: ^6.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgicons/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
